### ISSUE TITLE
WiFi-Bee Firmware Update: Images missing and wrong markdown

### ISSUE THREAD

**Issue by mpfeil** [sensebox/books-v2#108]
Images in book `edu` and `home` in chapter `Firmware Update WiFi-Bee` (additional-info.md) are missing.
Markdown syntax in book `home` in chapter `Firmware Update WiFi-Bee` is wrong:
```
Zuerst muss rausgefunden werden, welche Version das gelieferte WiFi-Bee hat. Gehe dazu auf ´´Datei´´; ´´Beispiele´´ und unter "Beispiele für senseBox MCU" auf ´´Test_WINC1500´´
```

**Comment by bkari02** [comment]
Solved with [commit for edu](https://github.com/sensebox/books-v2/commit/089709023729fb3700136d9f6b44a4e1c9f7b04a), [commit for home](https://github.com/sensebox/books-v2/commit/8f9c9ffaaaf4f627128b08640cc801b11e6dc12a).
