### ISSUE TITLE
Komponenten: GPS Modul

### ISSUE THREAD

**Issue by synolus-david** [sensebox/books-v2#20]
Beschreibung des GPS Moduls

**Comment by synolus-david** [comment]
@bkari02 @jasperbuss klärt das nochmal wer das macht!

**Comment by Thiemann96** [comment]
Done, muss noch in gh-pages gepusht werden mache ich wenn ich die anderen Issues schließe !

**Comment by synolus-david** [comment]
jo irgendwa shat da nicht geklappt? ist in keinem der books drin, könnt ihr das checken? @bkari02 @Thiemann96

**Comment by bkari02** [comment]
is done @Thiemann96, right?
