### ISSUE TITLE
Kapital: Projekte (Paket 4) - Sonstige Teile

### ISSUE THREAD

**Issue by synolus-david** [sensebox/books-v2#27]
Im Prinzip aus dem Alten Buch die Kapitel: 4.6 bis 4.11 umschreiben. Eventuell andere Kapitelnamen überlegen.

**Comment by synolus-david** [comment]
@Thiemann96 ist auch noch n offener Punkt :-)

**Comment by Thiemann96** [comment]
Genau , dafür bräuchte ich Beispielprojekte die schon mit der senseBox gemacht wurden , vielleicht etwas was im Rahmen von Mundus Projekten der letzten Woche entstanden sind ? @msh777 @mariopesch

**Comment by Thiemann96** [comment]
Ist zu mit #71
