### ISSUE TITLE
Changing Values on Display for :home

### ISSUE THREAD

**Issue by synolus-david** [sensebox/books-v2#33]
Jemand kann für den Display dokumentieren wie man baut, dass der die Werte hintereinander angezeigt werden. Es gibt doch einige die n Display zur home kaufen. Den Code gibts auch schon, bei mir Nachfragen.

**Comment by bkari02** [comment]
Erledigt mit commit [77b6bdcc0b7899e261ea6f283cdddab7804a2673](https://github.com/sensebox/books-v2/commit/ca6323d4e0f60434be4a8cc62661153946449791).

Unter Komponenten > Zubehör > LED-DIsplay zu finden. Siehe [hier](https://sensebox.github.io/books-v2/edu/de/komponenten/zubehoer/led-display.html).
