### ISSUE TITLE
Neues Kapitel: Sensor manuell hinzufügen

### ISSUE THREAD

**Issue by mpfeil** [sensebox/books-v2#42]
Schaut euch mal meinen Kommentar hier an:
https://forum.sensebox.de/t/installation-des-feinstaubsensors-sds011/200

Vielleicht können wir noch ein Kapitel einfügen, wie man nachträglich einen Sensor hinzufügen kann.

**Comment by synolus-david** [comment]
Wäre eventuell was für @Thiemann96 ?
