### ISSUE TITLE
Translate :home & :edu Book into English

### ISSUE THREAD

**Issue by synolus-david** [sensebox/books-v2#46]
It's a torture but necessary ;-) 

A task for the summer?

@buchwaldchassee 
@umut0 
@jasperbuss 
@Thiemann96 
@bkari02

**Comment by Thiemann96** [comment]
Uff... hat da nicht jemand @mariopesch ? schon was zu gemacht ?

**Comment by Thiemann96** [comment]
Wollten abwarten bis das deutsche Book komplett fertiggestellt ist und dann in einem Sprint das ins Englische übersetzen. Die "Architektur" würden wir anlehnen an das [Blockly Buch](https://sensebox.github.io/books-v2/blockly/).

**Comment by bkari02** [comment]
Home Buch wurde übersetzt. 
Bitte alle einmal durchlesen und Fehler beheben, bzw Issues und Pull-Request stellen. 
[Hier der Link zum Buch](https://sensebox.github.io/books-v2/home/)

@buchwaldchassee 
@umut0 
@jasperbuss 
@Thiemann96 
@synolus-david 
@mariopesch 
@bgunt
