### ISSUE TITLE
Umweltmessstation Unterrichtseinheit

### ISSUE THREAD

**Issue by bkari02** [sensebox/books-v2#47]
Unterrichtseinheit fuer das Futurium erstellen. Direkt in die Books integrieren als Beispiel, Thomas nimmt dann aus den Books den Content und passt es an das Design vom Futurium an und schickt es denen.

Deadline: Ende August

**Comment by Thiemann96** [comment]
Ersten Entwurf erstellt im Branch futurium_wetterstation.

**Comment by bkari02** [comment]
done?

**Comment by Thiemann96** [comment]
Glaub schon oder ? @cherry13579  ??
