### ISSUE TITLE
Komponenten/Zubehör/Gehäuse: Image link broken

### ISSUE THREAD

**Issue by johnjohndoe** [sensebox/books-v2#73]
The image on this [page](https://github.com/sensebox/books-v2/blob/edu/de/komponenten/zubehoer/gehaeuse.md) is not shown.

**Comment by bkari02** [comment]
fixed #6ec3f63055315d2b7c80f2cbb2002f95fde61b18 see [page](https://sensebox.github.io/books-v2/edu/de/komponenten/zubehoer/gehaeuse.html)

**Comment by bkari02** [comment]
fixed [here](https://github.com/sensebox/books-v2/commit/6ec3f63055315d2b7c80f2cbb2002f95fde61b18), see [page](https://sensebox.github.io/books-v2/edu/de/komponenten/zubehoer/gehaeuse.html)
